### ISSUE TITLE
merge the svg_compositor branch

### ISSUE THREAD

**Issue by nzjrs** [btel/svg_utils#13]
Not sure where else to comment, but I just wanted to say I am using the svg_compositor branch with some sucess. I have only encountered one problem - matplotlib emits svg figures with 'pt' (not px/cm) dimensions, which break the `Unit()` class.

Thanks a lot for your software!

**Comment by btel** [comment]
Hi, Thanks for the comment. It's great to hear that you use the new API. It's still not officially released, because I haven't written any documentation yet. It will come very soon.

Could you show a piece of code along a simple matplotlib figure showing the problem with `Unit` class? If possible please send it in a separate issue.
